name: Workflow de Bienvenida

# Evento que dispara la secuencia (un push a la rama main)
on:
  push:
    branches: [ main, master ]

jobs:
  saludo:
    # El entorno virtual o "runner" donde se ejecuta
    runs-on: ubuntu-latest

    steps:
    - name: Imprimir saludo en consola
      run: echo "¡Hola GitHub Actions! El workflow se ejecuto correctamente."
